- name: Install zsh
  become: true
  apt:
    name: zsh

- name: Make zsh the default shell
  become: true
  command: usermod --shell /bin/zsh {{ wsl_user }}

# zsh4humans bootstraps zsh and its configurations from .zshenv & .zshrc as soon as a the first zsh terminal is started!
# zsh4humans from: https://github.com/romkatv/zsh4humans
