- name: Install zsh
  become: true
  apt:
    name: zsh

- name: Make zsh the default shell
  become: true
  command: usermod --shell /bin/zsh {{ wsl_user }}

# Bootstrap command taken from: https://github.com/romkatv/zsh4humans/issues/94#issuecomment-764452003
- name: Bootstrap zsh4humans
  command: /usr/bin/bash -lc "script -qec 'zsh -is </development/null' /development/null"
