- hosts: localhost
  ### Go here to edit variables ###
  vars_files:
    - vars/prerequisite_packages.yml
    - vars/user_environment.yml
    - vars/versions.yml
  ### Comment out roles you don't need ###
  roles:
    - packages
    - shell
    - workspace
    # - ops  # TODO: for now... Check what we really need...
    - dev
  ### Change to your user! ###
  user: jancaron
