- hosts: localhost
  ### Go here to edit variables ###
  vars_files:
    - vars/packages.yml
    - vars/user.yml
    - vars/versions.yml
  ### Comment out roles you don't need ###
  roles:
    - packages
    - shell
    - workspace
    - orchestration
    - development
  ### Change to your user! ###
  user: jancaron
