- name: Add apt repositories
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  with_items: "{{ apt_repositories }}"

- name: Update package list
  become: true
  package:
    update_cache: yes

- name: Upgrade all packages
  become: true
  package:
    name: "*"
    state: latest

- name: Install defined prerequisite packages
  become: true
  apt:
    name: "{{ prerequisite_packages }}"

- name: Install defined pipx tools
  command: /usr/bin/bash -lc "pipx install {{ item }}"
  with_items: "{{ pipx_tools }}"
