- name: Add apt repositories
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  with_items: "{{ apt_repositories }}"

- name: Update and upgrade all installed packages
  become: true
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: yes
    autoremove: yes

- name: Install defined prerequisite packages
  become: true
  ansible.builtin.apt:
    name: "{{ prerequisite_packages }}"

- name: Install defined pipx tools
  command: /usr/bin/bash -lc "pipx install {{ item }}"
  with_items: "{{ pipx_tools }}"
