- name: Add apt repositories
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  with_items: "{{ apt_repositories }}"

- name: Update and upgrade all installed packages
  become: true
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: yes
    autoremove: yes

- name: Install defined prerequisite packages
  become: true
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    update_cache: yes

- name: Install snap packages
  become: true
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default(false) }}"
    state: present
  loop: "{{ snap_packages }}"

- name: Check for uv
  stat: path=/$HOME/.local/bin/uv
  register: uv

- name: Install uv
  command: /usr/bin/bash -lc "curl -LsSf https://astral.sh/uv/install.sh | sh"
  when: not uv.stat.exists

- name: Install defined uv tools
  command: /usr/bin/bash -lc "uv tool install {{ item }}"
  with_items: "{{ uv_tools }}"
