- name: Add apt signing key to keyring
  become: true
  ansible.builtin.apt_key:
    url: "{{ item.key_url }}"
    keyring: "/etc/apt/keyrings/{{ item.name }}-archive-keyring.gpg"
  loop: "{{ apt_deb_repos }}"

- name: Add apt deb source repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/{{ item.name }}-archive-keyring.gpg] {{ item.repo_url }} {{ item.distribution }} {{ item.channel }}"
    state: present
  loop: "{{ apt_deb_repos }}"

- name: Add apt ppa source repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:{{ item }}"
    state: present
  loop: "{{ apt_ppa_repos }}"

- name: Update and upgrade all installed packages
  become: true
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: yes
    autoremove: yes

- name: Install defined prerequisite packages
  become: true
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    update_cache: yes

- name: Install snap packages
  become: true
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default(false) }}"
    state: present
  loop: "{{ snap_packages }}"

- name: Check for uv
  stat: path=/$HOME/.local/bin/uv
  register: uv

- name: Install uv
  command: /usr/bin/bash -lc "curl -LsSf https://astral.sh/uv/install.sh | sh"
  when: not uv.stat.exists

- name: Get installed uv tools
  command: /usr/bin/bash -lc "uv tool list"
  register: uv_tools_installed
  changed_when: false

- name: Install defined uv tools
  command: /usr/bin/bash -lc "uv tool install {{ item }}"
  when: "item|string not in uv_tools_installed.stdout_lines|map('regex_replace', '^\\s*-?\\s*', '')|list"
  with_items: "{{ uv_tools }}"
