# https://github.com/jdx/mise
# https://mise.jdx.dev
# https://blog.devops.dev/how-i-got-rid-of-asdf-direnv-and-pyenv-all-at-once-95cf18942c75

# Needed for mise shell completions, see: https://usage.jdx.dev/cli/
- name: Install usage for mise shell completions
  command: /usr/bin/bash -lc "eval \"$(/usr/bin/mise activate bash)\" && mise use --global usage"

- name: Configure mise
  command: /usr/bin/bash -lc "eval \"$(/usr/bin/mise activate bash)\" && mise settings set experimental true"

- name: Install mise completions
  command: /usr/bin/bash -lc "mise completion zsh > ~/.cache/zsh4humans/v5/zsh-completions/src/_mise"
