- name: Install Python dependencies
  become: true
  apt:
    name: "{{ python_dependencies }}"
  vars:
    python_dependencies:
    - build-essential
    - libbz2-development
    - libffi-development
    - liblzma-development
    - libncurses5-development
    - libreadline-development
    - libsqlite3-development
    - libssl-development
    - libxml2-development
    - libxmlsec1-development
    - llvm
    - tk-development
    - zlib1g-development

- name: Install Python
  command: /usr/bin/bash -lc "eval \"$(/usr/bin/mise activate bash)\" && mise use --global python@{{ python_version }}"
