---
- name: Clone asdf
  command: git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v{{ asdf_version }}
  args:
    creates: ~/.asdf

- name: Get installed asdf plugins
  command: /usr/bin/bash -lc ". ~/.asdf/asdf.sh && asdf plugin-list"
  register: asdf_plugins
  ignore_errors: yes

- name: Add asdf plugins
  command: /usr/bin/bash -lc ". ~/.asdf/asdf.sh && asdf plugin-add {{ item }}"
  when: "item|string not in asdf_plugins.stdout_lines"
  with_items:
    - python
