---
- name: Install Python dependencies
  become: true
  apt:
    name: "{{ python_dependencies }}"
  vars:
    python_dependencies:
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libreadline-dev
    - pipx
    # TODO: NEEDS `pipx ensurepath` at some point! Maybe move to dev -> Python? Likely done by pulling .zshrc with PATH already set

- name: Install Python
  command: /usr/bin/bash -lc ". ~/.asdf/asdf.sh && asdf install python {{ python_version }}"

- name: Set global Python
  command: /usr/bin/bash -lc ". ~/.asdf/asdf.sh && asdf global python {{ python_version }}"

- name: Install virtualenv  # TODO: Do we want this? What about poetry? Use asdf instead?
  command: pipx install virtualenv
