- name: Install Python dependencies
  become: true
  apt:
    name: "{{ python_dependencies }}"
  vars:
    python_dependencies:
    - build-essential
    - libbz2-dev
    - libffi-dev
    - liblzma-dev
    - libncurses5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxmlsec1-dev
    - llvm
    - tk-dev
    - zlib1g-dev

- name: Install Python
  command: /usr/bin/bash -lc "eval \"$(/usr/bin/mise activate bash)\" && mise use --global python@{{ python_version }}"
