- name: Install Python dependencies
  become: true
  apt:
    name: "{{ python_dependencies }}"
  vars:
    python_dependencies:
    - build-essential
    - libbz2-dev
    - libffi-dev
    - liblzma-dev
    - libncurses5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxmlsec1-dev
    - llvm
    - tk-dev
    - zlib1g-dev

- name: Install Python
  command: /usr/bin/bash -lc ". ~/.asdf/asdf.sh && asdf install python {{ python_version }}"

- name: Set global Python
  command: /usr/bin/bash -lc ". ~/.asdf/asdf.sh && asdf global python {{ python_version }}"

- name: Install virtualenv via pipx  # TODO: Do we want this? What about poetry? Use asdf instead?
  command: pipx install virtualenv
