# Reference: https://github.com/nagygergo/jetbrains-toolbox-install

- name: Install JetBrains toolbox dependencies
  become: true
  apt:
    name: "{{ toolbox_dependencies }}"
  vars:
    toolbox_dependencies:
    - dbus-x11
    - libfontconfig
    - libfuse2
    - libgtk-3-bin
    - libx11-6
    - libx11-data
    - libx11-dev
    - libx11-protocol-perl
    - libx11-xcb1
    - libxi6
    - libxrender1
    - libxtst6
    - mesa-utils
    - tar
    - xdg-utils
    - x11-common
    - x11-utils
    - x11-xserver-utils
    - x11proto-core-dev
    - x11proto-dev

- name: Check for jetbrains-toolbox
  stat: path=/$HOME/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox
  register: toolbox

# Reduced version of script: https://github.com/nagygergo/jetbrains-toolbox-install/blob/master/jetbrains-toolbox.sh
- name: Install JetBrains toolbox
  shell: |
    set -x; cd "$(mktemp -d)" &&
    
    echo -e "\e[94mFetching the URL of the latest version...\e[39m" &&
    ARCHIVE_URL=$(curl -s 'https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release' | grep -Po '"linux":.*?[^\\]",' | awk -F ':' '{print $3,":"$4}'| sed 's/[", ]//g') &&
    ARCHIVE_FILENAME=$(basename "$ARCHIVE_URL") &&

    echo -e "\e[94mDownloading $ARCHIVE_FILENAME...\e[39m" &&
    wget -q --show-progress -cO "./$ARCHIVE_FILENAME" "$ARCHIVE_URL" &&

    INSTALL_DIR="$HOME/.local/share/JetBrains/Toolbox/bin" &&
    echo -e "\e[94mExtracting to $INSTALL_DIR...\e[39m" &&
    mkdir -p "$INSTALL_DIR" &&
    mkdir -p "$HOME/.local/bin" &&
    tar -xzf "./$ARCHIVE_FILENAME" -C "$INSTALL_DIR" --strip-components=1 &&
    chmod +x "$INSTALL_DIR/jetbrains-toolbox"
  when: not toolbox.stat.exists

- name: Create a symbolic link to the JetBrains toolbox
  file:
    src: "$HOME/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox"
    dest: '{{ lookup("env", "HOME") }}/.local/bin/jetbrains-toolbox'
    owner: "{{ wsl_user }}"
    group: "{{ wsl_user }}"
    state: link
